### ISSUE TITLE
License

### ISSUE THREAD

**Issue by woylie** [iosphere/elm-i18n#16]
Apparently this package is not maintained anymore. I would like to fork it to make some modifications and update it for Elm 0.19, but there is [no license](https://choosealicense.com/no-permission/) file included, so I cannot use it in my project without feeling queasy. Even if you don't feel like working on this package anymore, would you be so kind and add a license file so that we can keep this package alive? @felixLam

**Comment by felixLam** [comment]
Sorry for the omission. I am very busy on a few other projects right now. But the License is MIT

**Comment by carlfredrikhero** [comment]
@woylie I'm also interested in a 0.19 version of this package. Have you had any chance to work on it? Otherwise maybe we can fork it as a community package?

**Comment by klaftertief** [comment]
I'm happy to start maintaining the package again in the next couple of days.

**Comment by felixLam** [comment]
Added a license file and added @klaftertief as a contributor.
